# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-03 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200603_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
